name: Deploy Bambu API

on:
  pull_request:
    branches:
      - master
#on:
#  push:
#    branches:
#      - master

jobs:
  check-changes:
    name: Check Bambu API Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect_changes.outputs.bambu_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes in Bambu API
        id: detect_changes
        run: |
          bambu_changed="false"
          if git diff --name-only HEAD^ HEAD | grep -q 'vlxtr-bambu-api.yaml'; then
            bambu_changed="true"
          fi
          echo "bambu_changed=$bambu_changed" >> $GITHUB_ENV
          echo "::set-output name=bambu_changed::$bambu_changed"

  deploy-bambu:
    name: Deploy Bambu API
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Configure GitHub Packages Authentication
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.TOKEN_GITHUB }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Increment version for Bambu API
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -pl vlxtr-bambu-api -q -DforceStdout)
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_VERSION="$major.$((minor + 1)).0"
          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false -pl vlxtr-bambu-api
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit updated version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add vlxtr-bambu-api/pom.xml
          git commit -m "chore: Bump Bambu API version to $NEW_VERSION [skip ci]"
          git push https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}.git HEAD:master

      - name: Deploy Bambu API
        run: mvn clean deploy -pl vlxtr-bambu-api
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
