name: Deploy Swagger to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch name
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create specs directory and ensure index.html is at root
        run: |
          mkdir -p docs/specs
          # Make sure there's no README.md in the docs folder that would override index.html
          rm -f docs/README.md

      - name: Create or verify index.html
        run: |
          cat > docs/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>VLXTR API Documentation</title>
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.3/swagger-ui.min.css">
              <style>
                  body {
                      margin: 0;
                      padding: 0;
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                  }
                  .navbar {
                      background-color: #2c3e50;
                      padding: 1rem;
                      color: white;
                      display: flex;
                      flex-direction: column;
                  }
                  .navbar h1 {
                      margin: 0;
                      margin-bottom: 1rem;
                  }
                  .tabs {
                      display: flex;
                      gap: 0.5rem;
                  }
                  .tab {
                      padding: 0.5rem 1rem;
                      background-color: #34495e;
                      border-radius: 4px;
                      color: white;
                      text-decoration: none;
                      cursor: pointer;
                      transition: background-color 0.3s;
                  }
                  .tab:hover, .tab.active {
                      background-color: #3498db;
                  }
                  #swagger-ui {
                      margin: 1rem;
                  }
              </style>
          </head>
          <body>
              <div class="navbar">
                  <h1>VLXTR API Documentation</h1>
                  <div class="tabs">
                      <a class="tab" data-spec="allegro" href="#allegro">Allegro API</a>
                      <a class="tab" data-spec="gateway" href="#gateway">API Gateway</a>
                      <a class="tab" data-spec="bambu" href="#bambu">Bambu API</a>
                      <a class="tab" data-spec="core" href="#core">Core API</a>
                  </div>
              </div>

              <div id="swagger-ui"></div>

              <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.3/swagger-ui-bundle.min.js"></script>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.3/swagger-ui-standalone-preset.min.js"></script>

              <script>
                  const specs = {
                      allegro: "specs/vlxtr-allegro-api.yaml",
                      gateway: "specs/vlxtr-api-gateway.yaml",
                      bambu: "specs/vlxtr-bambu-api.yaml",
                      core: "specs/vlxtr-core-api.yaml"
                  };

                  let ui;

                  function initSwaggerUI(specUrl) {
                      if (ui) {
                          ui.specActions.updateUrl(specUrl);
                          ui.specActions.download();
                      } else {
                          ui = SwaggerUIBundle({
                              url: specUrl,
                              dom_id: '#swagger-ui',
                              deepLinking: true,
                              presets: [
                                  SwaggerUIBundle.presets.apis,
                                  SwaggerUIStandalonePreset
                              ],
                              layout: "StandaloneLayout"
                          });
                      }
                  }

                  function setActiveTab(id) {
                      document.querySelectorAll('.tab').forEach(tab => {
                          if (tab.dataset.spec === id) {
                              tab.classList.add('active');
                          } else {
                              tab.classList.remove('active');
                          }
                      });
                  }

                  // Handle tab clicks
                  document.querySelectorAll('.tab').forEach(tab => {
                      tab.addEventListener('click', (e) => {
                          e.preventDefault();
                          const specId = tab.dataset.spec;
                          initSwaggerUI(specs[specId]);
                          setActiveTab(specId);
                          window.location.hash = specId;
                      });
                  });

                  // Check hash on page load
                  document.addEventListener('DOMContentLoaded', () => {
                      let specId = window.location.hash.substring(1) || 'allegro'; // Default to allegro if no hash
                      if (!specs[specId]) {
                          specId = 'allegro'; // Fallback if invalid hash
                      }
                      initSwaggerUI(specs[specId]);
                      setActiveTab(specId);
                  });
              </script>
          </body>
          </html>
          EOL

      # Copy YAML files to docs/specs
      - name: Copy YAML files to docs/specs
        run: |
          cp vlxtr-allegro-api/vlxtr-allegro-api.yaml docs/specs/
          cp vlxtr-api-gateway/vlxtr-api-gateway.yaml docs/specs/
          cp vlxtr-bambu-api/vlxtr-bambu-api.yaml docs/specs/
          cp vlxtr-core-api/vlxtr-core-api.yaml docs/specs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
